version: '3.8'

services:
  frontend:
    build: ./frontend
    depends_on: #start backend before frontend
      - backend
    env_file: ./.env
    ports:
      - "4430:443"
    networks:
      - network-transcendence
    restart: always

  backend:
    build: ./backend
    depends_on: #start database before backend
      - database
    env_file: ./.env
    networks:
      - network-transcendence
    expose:
      - 8000
    volumes:
      - ./backend/:/app/ #mounts /backend on /app in the container so the code and files match
    restart: always

  database:
    build: ./database
    env_file: ./.env
    networks:
      - network-transcendence
    volumes:
      - postgres_data:/var/lib/postgresql/data/ #mounting so data persists across container restarts
    restart: always

volumes:
  postgres_data:

networks:
  network-transcendence:
    driver: bridge #default network driver for docker