FROM postgres:16.1-alpine3.19

#automatic configuration with env variables

#to connect to the running PostrgresSQL container :
#docker exec -it database bash
#psql -U postgres -d postgres
#\list or \dt
